version: '3.8'

services:
  app:
    build:
      context: .
    image: aplug-vitkac-app
    container_name: aplug-vitkac-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-net
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=aplug-vitkac
      - DB_USERNAME=root
      - DB_PASSWORD=root
    command: sh -c "/var/www/setup_venv.sh && php-fpm"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - laravel-net
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aplug-vitkac
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - laravel-net
    depends_on:
      - db

networks:
  laravel-net:
    driver: bridge

volumes:
  dbdata:
